const departments = [
    "AUDITORIA INTERNA",
    "CONSULTORIA JURIDICA",
    "DIRECCION GENERAL",
    "GERENCIA DE ATENCION INTEGRAL Y PREVENCION DE LA VIOLENCIA CONTRA LAS MUJERES",
    "GERENCIA DE DESARROLLO ALTERNATIVO Y POLITICA REGIONAL",
    "GERENCIA DE INVESTIGACION Y CAPACITACION",
    "GERENCIA DE LA DEFENSORIA NACIONAL DE LOS DERECHOS DE LA MUJER",
    "OFICINA DE ADMINISTRACION Y SERVICIOS",
    "OFICINA DE ATENCION A LA CIUDADANIA",
    "OFICINA DE COMUNICACION E IMAGEN INSTITUCIONAL",
    "OFICINA DE PLANIFICACION ORGANIZACION Y PRESUPUESTO",
    "OFICINA DE RECURSOS HUMANOS",
    "OFICINA DE RELACIONES INTERNACIONALES",
    "OFICINA DE SISTEMAS Y TECNOLOGIA DE LA INFORMACION"
];

export default departments;